# Generated by Django 4.1.7 on 2023-03-03 18:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('job', models.CharField(choices=[('', 'Select a job'), ('Full-Stack', 'Full-Stack'), ('Frontend', 'Frontend'), ('Backend', 'Backend')], max_length=50, null=True, verbose_name='Job type')),
                ('birth', models.DateField(verbose_name='Birthday')),
                ('phone', models.CharField(max_length=25)),
                ('personality', models.CharField(choices=[('', 'Select a personality'), ('I am outgoing', 'I am outgoing'), ('I am sociable', 'I am sociable'), ('I am antisocial', 'I am antisocial'), ('I am serious', 'I am serious')], max_length=50, null=True)),
                ('salary', models.CharField(choices=[('', 'Salary expectation (month)'), ('Between (3 Lakhs and 4 Lakhs)', 'Between (3 Lakhs and 4 Lakhs)'), ('Between (4 Lakhs and 5 Lakhs)', 'Between (4 Lakhs and 5 Lakhs)'), ('Between (5 Lakhs and 7 Lakhs)', 'Between (5 Lakhs and 7 Lakhs)'), ('Between (7 Lakhs and 10 Lakhs)', 'Between (7 Lakhs and 10 Lakhs)')], max_length=50, verbose_name='Salary expectation')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=6)),
                ('experience', models.BooleanField(null=True)),
                ('smoker', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='', max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(verbose_name='Presentation')),
                ('files', models.FileField(blank=True, upload_to='resume', verbose_name='Resume')),
                ('image', models.ImageField(blank=True, upload_to='photo', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Situation', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50, null=True)),
                ('company_note', models.TextField(blank=True)),
                ('frameworks', multiselectfield.db.fields.MultiSelectField(choices=[('Laravel', 'Laravel'), ('Angular', 'Angular'), ('Django', 'Django'), ('Flask', 'Flask'), ('Vue', 'Vue'), ('Others', 'Others')], default='', max_length=50)),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('Java', 'Java'), ('C++', 'C++'), ('Ruby', 'Ruby'), ('Others', 'Others')], default='', max_length=50)),
                ('databases', multiselectfield.db.fields.MultiSelectField(choices=[('MySql', 'MySql'), ('Postgre', 'Postgre'), ('MongoDB', 'MongoDB'), ('SqLite3', 'SqLite3'), ('Oracle', 'Oracle'), ('Others', 'Others')], default='', max_length=50)),
                ('libraries', multiselectfield.db.fields.MultiSelectField(choices=[('Ajax', 'Ajax'), ('Jquery', 'Jquery'), ('React.js', 'React.js'), ('Chart.js', 'Chart.js'), ('Gsap', 'Gsap'), ('Others', 'Others')], default='', max_length=50)),
                ('mobile', multiselectfield.db.fields.MultiSelectField(choices=[('React native', 'React native'), ('Kivy', 'Kivy'), ('Flutter', 'Flutter'), ('Ionic', 'Ionic'), ('Xamarin', 'Xamarin'), ('Others', 'Others')], default='', max_length=50)),
                ('others', multiselectfield.db.fields.MultiSelectField(choices=[('UML', 'UML'), ('SQL', 'SQL'), ('Docker', 'Docker'), ('GIT', 'GIT'), ('GraphQL', 'GraphQL'), ('Others', 'Others')], default='', max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('started_course', models.DateField(blank=True, null=True)),
                ('finished_course', models.DateField(blank=True, null=True)),
                ('about_course', models.TextField()),
                ('status_course', models.CharField(choices=[('', 'Select your status'), ("I'm studying", "I'm studying"), ('I took a break', 'I took a break'), ('Completed', 'Completed')], max_length=50, null=True)),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('started_job', models.DateField(blank=True, null=True)),
                ('finished_job', models.DateField(blank=True, null=True)),
                ('about_job', models.TextField()),
                ('employed', models.BooleanField(null=True, verbose_name="I'm employed")),
                ('remote', models.BooleanField(null=True, verbose_name='I agree to work remotely')),
                ('travel', models.BooleanField(null=True, verbose_name="I'm available for travel")),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
